<a href="https://colab.research.google.com/github/dixiong777/DL_Pytorch/blob/master/Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##  Introduction
[Reference](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

Minor changes for self learning.

In [1]:
# Other useful packages
import timeit
from __future__ import print_function
import random

### 1. Pytorch v.s. Numpy

In [2]:
import torch
x = torch.rand(5, 3)
print(x)
timeit.timeit(lambda: torch.rand(5, 3), number=10000)

tensor([[0.6981, 0.1938, 0.3427],
        [0.9560, 0.3272, 0.5232],
        [0.9518, 0.0507, 0.8357],
        [0.9435, 0.3506, 0.1860],
        [0.7871, 0.3632, 0.8484]])


0.0303088290000062

In [3]:
import numpy
y = numpy.random.rand(5, 3)
print(y)
timeit.timeit(lambda: numpy.random.rand(5, 3), number=10000)

[[0.48099589 0.33722123 0.59573407]
 [0.42382522 0.06970274 0.8924247 ]
 [0.02763591 0.71490617 0.99793645]
 [0.87381804 0.49926191 0.29942192]
 [0.75129338 0.54411587 0.03767811]]


0.013861125000005359

### 2. Generate a Matrix

#### Empty Matrix
An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

#### Random Matrix
Use `torch.manual_seed(0)` to set seed instead of `random.rand(0)`.

#### Zero Matrix

In [4]:
# Empty Matrix: Results can be different even with a specific seed.
torch.manual_seed(0)
x = torch.empty(5, 3)
print(x)

tensor([[1.0278e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 2.6931e-01],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 9.3849e-01]])


In [5]:
# Random Matrix:
torch.manual_seed(0)
x = torch.rand(5, 3)
print(x)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])


In [6]:
# Zero Matrix: If not specific type, it will be float.
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### 3. Create a tensor
Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [7]:
# Create a new tensor
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
# Generate from an existing tensor.
# Default toch.dtype and torch.device are same as that of x.
y = x.new_ones(5, 3, dtype = torch.double)
print(y)
print(y.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.Size([5, 3])


In [9]:
# Override dtype and values but with the same size of y
# randomn - from a normal distribution. 
z = torch.randn_like(y, dtype = torch.float)
print(z)

tensor([[ 0.6035,  0.8110, -0.0451],
        [ 0.8797,  1.0482, -0.0445],
        [-0.7229,  2.8663, -0.5655],
        [ 0.1604, -0.0254,  1.0739],
        [ 2.2628, -0.9175, -0.2251]])


In [10]:
# Size
# torch.Size() is a tuple (a row of record) so it supports all tuple operations.
print(z.size())

torch.Size([5, 3])


### 4. Operations

* Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

* More Operations are avaliable here [https://pytorch.org/docs/stable/torch.html]
    1. Tensors
    2. Generators
    3. Random Sampling
    4. Serialization
    5. Parallelism
    6. Locally Disabling Gradient Computation
    7. Match Operations

In [11]:
# Addition:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print('x = ', x)
print('y = ', y)

## Direct way:
print('x + y =', x + y)

## Function:
print('x + y = ', torch.add(x, y))

## Store the result.
result = torch.empty(5, 3)
print('x + y = ', torch.add(x, y, out = result))
print('Stored result is', result)

## Function on one of the variable:
print('Add x to y:', y.add_(x))
print('And the y will be updated as', y)

x =  tensor([[0.7932, 0.2783, 0.4820],
        [0.8198, 0.9971, 0.6984],
        [0.5675, 0.8352, 0.2056],
        [0.5932, 0.1123, 0.1535],
        [0.2417, 0.7262, 0.7011]])
y =  tensor([[0.2038, 0.6511, 0.7745],
        [0.4369, 0.5191, 0.6159],
        [0.8102, 0.9801, 0.1147],
        [0.3168, 0.6965, 0.9143],
        [0.9351, 0.9412, 0.5995]])
x + y = tensor([[0.9970, 0.9293, 1.2564],
        [1.2567, 1.5162, 1.3143],
        [1.3777, 1.8153, 0.3203],
        [0.9099, 0.8089, 1.0677],
        [1.1768, 1.6674, 1.3006]])
x + y =  tensor([[0.9970, 0.9293, 1.2564],
        [1.2567, 1.5162, 1.3143],
        [1.3777, 1.8153, 0.3203],
        [0.9099, 0.8089, 1.0677],
        [1.1768, 1.6674, 1.3006]])
x + y =  tensor([[0.9970, 0.9293, 1.2564],
        [1.2567, 1.5162, 1.3143],
        [1.3777, 1.8153, 0.3203],
        [0.9099, 0.8089, 1.0677],
        [1.1768, 1.6674, 1.3006]])
Stored result is tensor([[0.9970, 0.9293, 1.2564],
        [1.2567, 1.5162, 1.3143],
        [1.3777, 1.8153,

### 5. Index
Similiar to the Numpy.

In [12]:
print(x[:, 1])

tensor([0.2783, 0.9971, 0.8352, 0.1123, 0.7262])


In [13]:
# If only one element, we can view it as a Python number using x.item()
# Will be error if more than one element.
x = torch.randn(1)
print(x)
print(x.item())

tensor([2.3466])
2.3466382026672363


###  6. Reshape and Resize:

* torch.view()

In [14]:
# Generate x from a standard normal distribution
x = torch.randn(4, 4)
print(x)

# Reshape to 2 * 8 matrix instead.
y = x.view(2, 8)
print(y)

# Automatically calculate the other dimension. 
z = x.view(-1, 16)
print(z)

# Print all sizes:
print('size of x:', x.size())
print('size of y:', y.size())
print('size of z:', z.size())

tensor([[-3.1700e-01, -1.0925e+00, -8.5194e-02, -9.3348e-02],
        [ 6.8705e-01, -8.3832e-01,  8.9182e-04,  8.4189e-01],
        [ 1.8541e-01,  6.2114e-01,  6.3818e-01, -2.4600e-01],
        [ 2.3025e+00, -1.8817e+00, -4.9727e-02, -1.0450e+00]])
tensor([[-3.1700e-01, -1.0925e+00, -8.5194e-02, -9.3348e-02,  6.8705e-01,
         -8.3832e-01,  8.9182e-04,  8.4189e-01],
        [ 1.8541e-01,  6.2114e-01,  6.3818e-01, -2.4600e-01,  2.3025e+00,
         -1.8817e+00, -4.9727e-02, -1.0450e+00]])
tensor([[-3.1700e-01, -1.0925e+00, -8.5194e-02, -9.3348e-02,  6.8705e-01,
         -8.3832e-01,  8.9182e-04,  8.4189e-01,  1.8541e-01,  6.2114e-01,
          6.3818e-01, -2.4600e-01,  2.3025e+00, -1.8817e+00, -4.9727e-02,
         -1.0450e+00]])
size of x: torch.Size([4, 4])
size of y: torch.Size([2, 8])
size of z: torch.Size([1, 16])


### 7. Transfer to and from a Numpy array

* The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

* All the Tensors on the CPU except for the CharTensor support converting to NumPy and back.

In [15]:
# Converting a Torch Tensor to a Numpy Array
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

# If change on a, b will be changed as well.
a.add_(1)
print('After changing, a = ', a)
print('After changing, b = ', b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
After changing, a =  tensor([2., 2., 2., 2., 2.])
After changing, b =  [2. 2. 2. 2. 2.]


In [16]:
# Converting a Numpy Array to a Torch Tensor
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

# If change on a, b will be changed as well.
np.add(a, 1, out = a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### 8. CUDA Tensors

* Can move the tensors in and out of GPU using the `.to` method.

In [17]:
# Check whether CUDA is avaliable:
torch.cuda.is_available()

# Check the name of CUA
torch.cuda.get_device_name(0)

'Tesla T4'

In [18]:
# Move the tensors to the CUDA
# No CUDA support on the Mac....
if torch.cuda.is_available():
    device = torch.device('cuda')
    # Directly create a tensor on GPU
    y = torch.ones_like(x, device = device)
    # Move the tensor to GPU
    x = x.to(device)
    z = x + y
    print(z)
    
    # Move back to CPU
    print(z.to('cpu', torch.double))

tensor([[ 0.6830, -0.0925,  0.9148,  0.9067],
        [ 1.6871,  0.1617,  1.0009,  1.8419],
        [ 1.1854,  1.6211,  1.6382,  0.7540],
        [ 3.3025, -0.8817,  0.9503, -0.0450]], device='cuda:0')
tensor([[ 0.6830, -0.0925,  0.9148,  0.9067],
        [ 1.6871,  0.1617,  1.0009,  1.8419],
        [ 1.1854,  1.6211,  1.6382,  0.7540],
        [ 3.3025, -0.8817,  0.9503, -0.0450]], dtype=torch.float64)
